#secrets.toml

OPEN_API_KEY = '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'

url: str = "https://ybmodwxzybrtmunbomyg.supabase.co"
key: str = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlibW9kd3h6eWJydG11bmJvbXlnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNzg3OTI2OSwiZXhwIjoyMDIzNDU1MjY5fQ.bEifUDZUC3OGY8h6ZFtFoYZJJ9keEAmSZapdsqieZ_c"
